export type TemplateSection = { name: string; context: string }
export type TemplateEntry = { key: string; value: string; type?: string; sectionName: string }

export const WEBSITE_TEMPLATE: { sections: TemplateSection[]; entries: TemplateEntry[] } = {
  sections: [
    { name: 'Perfil do Negócio', context: 'website' },
    { name: 'Navegação',         context: 'website' },
    { name: 'Homepage',          context: 'website' },
    { name: 'Marcações',         context: 'website' },
    { name: 'Cancelamento',      context: 'website' },
    { name: 'Dashboard',         context: 'website' },
    { name: 'Autenticação',      context: 'website' },
    { name: 'Cards',             context: 'website' },
    { name: 'Editar marcação',   context: 'website' },
    { name: 'PWA',               context: 'website' },
    { name: 'Galeria',           context: 'website' },
    { name: 'SEO',               context: 'website' },
    { name: 'App',               context: 'website' },
  ],
  entries: [
    // ── Perfil do Negócio ────────────────────────────────────────────────────
    // Deixar em branco — preencher por cliente
    { key: 'perfil.nome',          value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.slogan',        value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.telefone',      value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.email',         value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.morada',        value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.cidade',        value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.codigo_postal', value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.mapa_url',      value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.instagram_url', value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.facebook_url',  value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.tiktok_url',    value: '', sectionName: 'Perfil do Negócio' },
    { key: 'perfil.horario',       value: '', sectionName: 'Perfil do Negócio' },

    // ── Navegação ─────────────────────────────────────────────────────────────
    { key: 'nav.inicio',                value: 'Início',                    sectionName: 'Navegação' },
    { key: 'nav.trabalhos',             value: 'Trabalhos',                 sectionName: 'Navegação' },
    { key: 'nav.sobre',                 value: 'Sobre',                     sectionName: 'Navegação' },
    { key: 'nav.conta',                 value: 'Conta',                     sectionName: 'Navegação' },
    { key: 'nav.sair',                  value: 'Sair',                      sectionName: 'Navegação' },
    { key: 'nav.entrar',                value: 'Entrar',                    sectionName: 'Navegação' },
    { key: 'nav.instalar',              value: 'Instalar',                  sectionName: 'Navegação' },
    { key: 'nav.instalar.titulo',       value: 'Instalar no iPhone / iPad', sectionName: 'Navegação' },
    { key: 'nav.instalar.ios.partilhar',value: 'Partilhar',                 sectionName: 'Navegação' },
    { key: 'nav.instalar.ios.ecra',     value: 'Adicionar ao ecrã inicial', sectionName: 'Navegação' },

    // ── Homepage ──────────────────────────────────────────────────────────────
    { key: 'home.contacto.titulo',       value: 'Contacto & Horário', sectionName: 'Homepage' },
    { key: 'home.contacto.morada.label', value: 'Morada',             sectionName: 'Homepage' },
    { key: 'home.contacto.horario.label',value: 'Horário',            sectionName: 'Homepage' },
    { key: 'home.booking.eyebrow',       value: 'Marcar',             sectionName: 'Homepage' },
    { key: 'home.booking.titulo',        value: 'Marca o teu corte',  sectionName: 'Homepage' },
    { key: 'home.booking.subtitulo',     value: 'em 3 passos',        sectionName: 'Homepage' },

    // ── Marcações ─────────────────────────────────────────────────────────────
    { key: 'booking.passo.1',           value: 'Serviço',                                                                         sectionName: 'Marcações' },
    { key: 'booking.passo.2',           value: 'Data & hora',                                                                     sectionName: 'Marcações' },
    { key: 'booking.passo.3',           value: 'Confirmar',                                                                       sectionName: 'Marcações' },
    { key: 'booking.continuar',         value: 'Continuar',                                                                       sectionName: 'Marcações' },
    { key: 'booking.voltar',            value: 'Voltar',                                                                          sectionName: 'Marcações' },
    { key: 'booking.data.label',        value: 'Data',                                                                            sectionName: 'Marcações' },
    { key: 'booking.data.outra',        value: 'Escolher outra data',                                                             sectionName: 'Marcações' },
    { key: 'booking.hora.label',        value: 'Hora disponível',                                                                 sectionName: 'Marcações' },
    { key: 'booking.sem_data',          value: 'Escolhe uma data primeiro.',                                                      sectionName: 'Marcações' },
    { key: 'booking.sem_horarios',      value: 'Sem horários disponíveis.',                                                       sectionName: 'Marcações' },
    { key: 'booking.resumo.titulo',     value: 'Resumo',                                                                          sectionName: 'Marcações' },
    { key: 'booking.resumo.servico',    value: 'Serviço:',                                                                        sectionName: 'Marcações' },
    { key: 'booking.resumo.data',       value: 'Data:',                                                                           sectionName: 'Marcações' },
    { key: 'booking.resumo.hora',       value: 'Hora:',                                                                           sectionName: 'Marcações' },
    { key: 'booking.resumo.cliente',    value: 'Cliente:',                                                                        sectionName: 'Marcações' },
    { key: 'booking.notas.label',       value: 'Notas (opcional)',                                                                sectionName: 'Marcações' },
    { key: 'booking.notas.placeholder', value: 'Algum pedido especial?',                                                          sectionName: 'Marcações' },
    { key: 'booking.confirmar',         value: 'Confirmar marcação',                                                              sectionName: 'Marcações' },
    { key: 'booking.sucesso.titulo',    value: 'Marcação confirmada!',                                                            sectionName: 'Marcações' },
    { key: 'booking.sucesso.mensagem',  value: 'Receberás um email com os detalhes e link de cancelamento.',                      sectionName: 'Marcações' },
    { key: 'booking.sucesso.ver',       value: 'Ver as minhas marcações',                                                         sectionName: 'Marcações' },
    { key: 'booking.sucesso.nova',      value: 'Nova marcação',                                                                   sectionName: 'Marcações' },

    // ── Cancelamento ──────────────────────────────────────────────────────────
    { key: 'cancel.titulo',               value: 'Cancelar marcação',                                                    sectionName: 'Cancelamento' },
    { key: 'cancel.carregando',           value: 'A carregar marcação…',                                                 sectionName: 'Cancelamento' },
    { key: 'cancel.nao_encontrada',       value: 'Marcação não encontrada',                                              sectionName: 'Cancelamento' },
    { key: 'cancel.nao_encontrada.msg',   value: 'O link pode ser inválido ou já ter expirado.',                         sectionName: 'Cancelamento' },
    { key: 'cancel.ja_cancelada',         value: 'Esta marcação já foi cancelada.',                                      sectionName: 'Cancelamento' },
    { key: 'cancel.ja_concluida',         value: 'Esta marcação já foi concluída.',                                      sectionName: 'Cancelamento' },
    { key: 'cancel.confirmar_texto',      value: 'Tens a certeza que queres cancelar esta marcação?',                    sectionName: 'Cancelamento' },
    { key: 'cancel.servico',              value: 'Serviço',                                                              sectionName: 'Cancelamento' },
    { key: 'cancel.data',                 value: 'Data',                                                                 sectionName: 'Cancelamento' },
    { key: 'cancel.hora',                 value: 'Hora',                                                                 sectionName: 'Cancelamento' },
    { key: 'cancel.preco',                value: 'Preço',                                                                sectionName: 'Cancelamento' },
    { key: 'cancel.estado',               value: 'Estado',                                                               sectionName: 'Cancelamento' },
    { key: 'cancel.erro',                 value: 'Não foi possível cancelar. Tenta novamente ou contacta-nos.',          sectionName: 'Cancelamento' },
    { key: 'cancel.a_cancelar',           value: 'A cancelar…',                                                         sectionName: 'Cancelamento' },
    { key: 'cancel.confirmar_btn',        value: 'Confirmar cancelamento',                                               sectionName: 'Cancelamento' },
    { key: 'cancel.sucesso.titulo',       value: 'Marcação cancelada',                                                   sectionName: 'Cancelamento' },
    { key: 'cancel.sucesso.mensagem',     value: 'Recebeste um email de confirmação. Esperamos ver-te em breve!',        sectionName: 'Cancelamento' },
    { key: 'cancel.status.pendente',      value: 'Pendente',                                                             sectionName: 'Cancelamento' },
    { key: 'cancel.status.confirmada',    value: 'Confirmada',                                                           sectionName: 'Cancelamento' },
    { key: 'cancel.status.concluida',     value: 'Concluída',                                                            sectionName: 'Cancelamento' },
    { key: 'cancel.status.cancelada',     value: 'Cancelada',                                                            sectionName: 'Cancelamento' },

    // ── Dashboard ─────────────────────────────────────────────────────────────
    { key: 'dashboard.voltar',                  value: 'Página inicial',                         sectionName: 'Dashboard' },
    { key: 'dashboard.ola',                     value: 'Olá,',                                   sectionName: 'Dashboard' },
    { key: 'dashboard.nova_marcacao',           value: '+ Nova marcação',                        sectionName: 'Dashboard' },
    { key: 'dashboard.sair',                    value: 'Sair',                                   sectionName: 'Dashboard' },
    { key: 'dashboard.proximas.titulo',         value: 'Próximas marcações',                     sectionName: 'Dashboard' },
    { key: 'dashboard.nenhuma',                 value: 'Nenhuma agendada.',                      sectionName: 'Dashboard' },
    { key: 'dashboard.pode_cancelar',           value: 'Podes cancelar até à data.',             sectionName: 'Dashboard' },
    { key: 'dashboard.carregando',              value: 'A carregar marcações…',                  sectionName: 'Dashboard' },
    { key: 'dashboard.erro',                    value: 'Erro ao carregar marcações:',             sectionName: 'Dashboard' },
    { key: 'dashboard.erro.reload',             value: 'tenta recarregar a página.',             sectionName: 'Dashboard' },
    { key: 'dashboard.sem_marcacoes',           value: 'Sem marcações',                          sectionName: 'Dashboard' },
    { key: 'dashboard.marcar_agora',            value: 'Marcar agora',                           sectionName: 'Dashboard' },
    { key: 'dashboard.historico.titulo',        value: 'Histórico',                              sectionName: 'Dashboard' },
    { key: 'dashboard.historico.carregando',    value: 'A carregar histórico…',                  sectionName: 'Dashboard' },
    { key: 'dashboard.historico.contagem',      value: 'marcação(ões)',                          sectionName: 'Dashboard' },
    { key: 'dashboard.conta.titulo',            value: 'Dados da conta',                         sectionName: 'Dashboard' },
    { key: 'dashboard.cancelar',                value: 'Cancelar',                               sectionName: 'Dashboard' },
    { key: 'dashboard.editar',                  value: 'Editar',                                 sectionName: 'Dashboard' },
    { key: 'dashboard.sucesso',                 value: 'Perfil actualizado com sucesso.',         sectionName: 'Dashboard' },
    { key: 'dashboard.nome',                    value: 'Nome *',                                 sectionName: 'Dashboard' },
    { key: 'dashboard.email',                   value: 'Email *',                                sectionName: 'Dashboard' },
    { key: 'dashboard.telemovel',               value: 'Telemóvel *',                            sectionName: 'Dashboard' },
    { key: 'dashboard.nif',                     value: 'NIF',                                    sectionName: 'Dashboard' },
    { key: 'dashboard.guardar',                 value: 'Guardar alterações',                     sectionName: 'Dashboard' },
    { key: 'dashboard.a_guardar',               value: 'A guardar…',                             sectionName: 'Dashboard' },
    { key: 'dashboard.cancelar_dialog.titulo',  value: 'Cancelar marcação',                      sectionName: 'Dashboard' },
    { key: 'dashboard.cancelar_dialog.texto',   value: 'Tens a certeza? Esta ação não pode ser revertida.', sectionName: 'Dashboard' },
    { key: 'dashboard.cancelar_dialog.a_cancelar', value: 'A cancelar…',                        sectionName: 'Dashboard' },
    { key: 'dashboard.cancelar_dialog.sim',     value: 'Sim, cancelar',                         sectionName: 'Dashboard' },
    { key: 'dashboard.cancelar_dialog.nao',     value: 'Voltar',                                 sectionName: 'Dashboard' },
    { key: 'dashboard.campo.nome',              value: 'Nome',                                   sectionName: 'Dashboard' },
    { key: 'dashboard.campo.email',             value: 'Email',                                  sectionName: 'Dashboard' },
    { key: 'dashboard.campo.telemovel',         value: 'Telemóvel',                              sectionName: 'Dashboard' },
    { key: 'dashboard.campo.nif',               value: 'NIF',                                    sectionName: 'Dashboard' },

    // ── Autenticação ──────────────────────────────────────────────────────────
    { key: 'auth.login.titulo',              value: 'Bem-vindo de volta',                                                              sectionName: 'Autenticação' },
    { key: 'auth.register.titulo',           value: 'Criar conta',                                                                     sectionName: 'Autenticação' },
    { key: 'auth.forgot.titulo',             value: 'Recuperar palavra-passe',                                                         sectionName: 'Autenticação' },
    { key: 'auth.reset.titulo',              value: 'Nova palavra-passe',                                                              sectionName: 'Autenticação' },
    { key: 'auth.google',                    value: 'Continuar com Google (brevemente)',                                               sectionName: 'Autenticação' },
    { key: 'auth.ou',                        value: 'ou',                                                                              sectionName: 'Autenticação' },
    { key: 'auth.email.label',               value: 'Email *',                                                                         sectionName: 'Autenticação' },
    { key: 'auth.email.placeholder',         value: 'email@exemplo.com',                                                               sectionName: 'Autenticação' },
    { key: 'auth.password.label',            value: 'Palavra-passe *',                                                                 sectionName: 'Autenticação' },
    { key: 'auth.esqueceu',                  value: 'Esqueceste?',                                                                     sectionName: 'Autenticação' },
    { key: 'auth.password.placeholder',      value: '••••••••',                                                                        sectionName: 'Autenticação' },
    { key: 'auth.a_processar',               value: 'A processar…',                                                                    sectionName: 'Autenticação' },
    { key: 'auth.entrar',                    value: 'Entrar',                                                                          sectionName: 'Autenticação' },
    { key: 'auth.sem_conta',                 value: 'Sem conta?',                                                                      sectionName: 'Autenticação' },
    { key: 'auth.registar',                  value: 'Regista-te',                                                                      sectionName: 'Autenticação' },
    { key: 'auth.nome.label',                value: 'Nome completo *',                                                                 sectionName: 'Autenticação' },
    { key: 'auth.nome.placeholder',          value: 'O teu nome',                                                                      sectionName: 'Autenticação' },
    { key: 'auth.telemovel.label',           value: 'Telemóvel',                                                                       sectionName: 'Autenticação' },
    { key: 'auth.telemovel.placeholder',     value: '+351 9XX XXX XXX',                                                                sectionName: 'Autenticação' },
    { key: 'auth.criar_conta',               value: 'Criar conta',                                                                     sectionName: 'Autenticação' },
    { key: 'auth.ja_tem_conta',              value: 'Já tens conta?',                                                                  sectionName: 'Autenticação' },
    { key: 'auth.entra',                     value: 'Entra',                                                                           sectionName: 'Autenticação' },
    { key: 'auth.email_enviado.titulo',      value: 'Email enviado!',                                                                  sectionName: 'Autenticação' },
    { key: 'auth.email_enviado.mensagem',    value: 'Se o email existir na nossa base de dados, receberás um link para redefinir a tua palavra-passe. Verifica também a pasta de spam.', sectionName: 'Autenticação' },
    { key: 'auth.voltar_login',              value: 'Voltar ao login',                                                                 sectionName: 'Autenticação' },
    { key: 'auth.instrucoes_email',          value: 'Introduz o teu email e enviamos um link para redefinires a palavra-passe.',       sectionName: 'Autenticação' },
    { key: 'auth.a_enviar',                  value: 'A enviar…',                                                                       sectionName: 'Autenticação' },
    { key: 'auth.enviar_link',               value: 'Enviar link',                                                                     sectionName: 'Autenticação' },
    { key: 'auth.password_alterada.titulo',  value: 'Palavra-passe alterada!',                                                         sectionName: 'Autenticação' },
    { key: 'auth.password_alterada.mensagem',value: 'Já podes entrar com a tua nova palavra-passe.',                                   sectionName: 'Autenticação' },
    { key: 'auth.instrucoes_reset',          value: 'Escolhe uma nova palavra-passe com pelo menos 8 caracteres.',                     sectionName: 'Autenticação' },
    { key: 'auth.nova_password.label',       value: 'Nova palavra-passe *',                                                            sectionName: 'Autenticação' },
    { key: 'auth.nova_password.placeholder', value: 'Mínimo 8 caracteres',                                                             sectionName: 'Autenticação' },
    { key: 'auth.confirmar_password.label',  value: 'Confirmar palavra-passe *',                                                       sectionName: 'Autenticação' },
    { key: 'auth.confirmar_password.placeholder', value: 'Repete a nova palavra-passe',                                               sectionName: 'Autenticação' },
    { key: 'auth.a_guardar',                 value: 'A guardar…',                                                                      sectionName: 'Autenticação' },
    { key: 'auth.guardar_password',          value: 'Guardar nova palavra-passe',                                                      sectionName: 'Autenticação' },
    { key: 'auth.erro.credenciais',          value: 'Email ou palavra-passe incorretos.',                                              sectionName: 'Autenticação' },
    { key: 'auth.erro.token',                value: 'Token inválido ou expirado. Pede um novo link.',                                  sectionName: 'Autenticação' },
    { key: 'auth.erro.email_registado',      value: 'Este email já está registado. Tenta entrar.',                                     sectionName: 'Autenticação' },
    { key: 'auth.erro.dados',                value: 'Dados inválidos. Verifica os campos.',                                            sectionName: 'Autenticação' },
    { key: 'auth.erro.generico',             value: 'Ocorreu um erro. Tenta novamente.',                                               sectionName: 'Autenticação' },

    // ── Cards de marcação ─────────────────────────────────────────────────────
    { key: 'card.confirmado', value: 'Confirmado', sectionName: 'Cards' },
    { key: 'card.cancelado',  value: 'Cancelado',  sectionName: 'Cards' },
    { key: 'card.pendente',   value: 'Pendente',   sectionName: 'Cards' },
    { key: 'card.concluido',  value: 'Concluído',  sectionName: 'Cards' },
    { key: 'card.editar',     value: 'Editar',     sectionName: 'Cards' },
    { key: 'card.cancelar',   value: 'Cancelar',   sectionName: 'Cards' },

    // ── Editar marcação ───────────────────────────────────────────────────────
    { key: 'edit.titulo',            value: 'Editar marcação',   sectionName: 'Editar marcação' },
    { key: 'edit.nova_data',         value: 'Nova data',         sectionName: 'Editar marcação' },
    { key: 'edit.nova_hora',         value: 'Nova hora',         sectionName: 'Editar marcação' },
    { key: 'edit.notas.label',       value: 'Notas',             sectionName: 'Editar marcação' },
    { key: 'edit.notas.placeholder', value: 'Notas...',          sectionName: 'Editar marcação' },
    { key: 'edit.guardar',           value: 'Guardar alterações',sectionName: 'Editar marcação' },

    // ── PWA ───────────────────────────────────────────────────────────────────
    { key: 'pwa.titulo',          value: 'Instalar a App',                                                                               sectionName: 'PWA' },
    { key: 'pwa.subtitulo',       value: 'Acesso rápido, sem abrir o browser.',                                                          sectionName: 'PWA' },
    { key: 'pwa.como',            value: 'Como?',                                                                                        sectionName: 'PWA' },
    { key: 'pwa.instalar',        value: 'Instalar',                                                                                     sectionName: 'PWA' },
    { key: 'pwa.ios.partilhar',   value: 'Partilhar',                                                                                    sectionName: 'PWA' },
    { key: 'pwa.ios.ecra',        value: 'Adicionar ao ecrã inicial',                                                                    sectionName: 'PWA' },
    { key: 'pwa.chrome.mensagem', value: 'Abre este site no Google Chrome e volta a tentar — o Chrome permite instalar a app directamente.', sectionName: 'PWA' },

    // ── Galeria ───────────────────────────────────────────────────────────────
    { key: 'galeria.alt_trabalho', value: 'Trabalho', sectionName: 'Galeria' },

    // ── SEO — deixar em branco para preencher por cliente ────────────────────
    { key: 'seo.home.titulo',       value: '', sectionName: 'SEO' },
    { key: 'seo.home.descricao',    value: '', sectionName: 'SEO' },
    { key: 'seo.galeria.titulo',    value: '', sectionName: 'SEO' },
    { key: 'seo.galeria.descricao', value: '', sectionName: 'SEO' },
    { key: 'seo.sobre.titulo',      value: '', sectionName: 'SEO' },
    { key: 'seo.sobre.descricao',   value: '', sectionName: 'SEO' },
    { key: 'seo.dashboard.titulo',  value: '', sectionName: 'SEO' },
    { key: 'seo.cancelar.titulo',   value: '', sectionName: 'SEO' },

    // ── App ───────────────────────────────────────────────────────────────────
    { key: 'app.bem_vindo', value: 'Bem-vindo,', sectionName: 'App' },
  ],
}
